spring.application.name=veterinaria

spring.datasource.url=jdbc:mysql://localhost:3311/veterinaria
spring.datasource.username=root
spring.datasource.password=Vete2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect